In [1]:
import numpy as np
import nashpy as nash

In [2]:
A=[[-1,-1/3,1/3,1],[0,0,0,0]]

In [13]:
B1=[[2,2,1,1],[4,4,3,3]]

In [14]:
B2=[[-1,1,-1,1],[0,3,0,3]]

In [15]:
game1=nash.Game(A,B1)
game2=nash.Game(A,B2)


In [17]:
game1

Bi matrix game with payoff matrices:

Row player:
[[-1.         -0.33333333  0.33333333  1.        ]
 [ 0.          0.          0.          0.        ]]

Column player:
[[2 2 1 1]
 [4 4 3 3]]

In [25]:
eq1=list(game1.support_enumeration())
eq1

[(array([0., 1.]), array([1., 0., 0., 0.])),
 (array([0., 1.]), array([0., 1., 0., 0.]))]

In [32]:
eq2=list(game2.support_enumeration())
eq2

[(array([1., 0.]), array([0., 0., 0., 1.])),
 (array([0., 1.]), array([0., 1., 0., 0.]))]

In [36]:
suporte=[[1,2,3,4],[5,6,7,8]] 
for s1,s2 in eq1:
    quadrante=np.dot(np.dot(s1,suporte),s2)
    print(quadrante)
    

5.0
6.0


In [37]:
for s1,s2 in eq2:
    quadrante=np.dot(np.dot(s1,suporte),s2)
    print(quadrante)
    

4.0
6.0
